// Generated by CoffeeScript 1.5.0
(function() {
  var app, express;

  express = require('express');

  app = express();

  console.log('Hello');

  app.get('/', function(req, res) {
    res.send('hello world');
    return console.log('Hi');
  });

  app.listen(3000);

}).call(this);
